#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

echo "==> Installing gem dependencies..."

gem list bundler -i &>/dev/null || {
  gem install bundler
}

bundle check &>/dev/null || {
  bundle install --quiet
}
