#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

script/update

expect -c "
  spawn bundle exec jekyll server $*
  expect \"Server running...\"
  exec open \"http://localhost:4000\"
  interact
"
